namespace: netapp
name: aws
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  netapp.ontap: '>=0.1.0'
repository: git@github.com:coll-test/netapp.aws.git
documentation: https://github.com/coll-test/netapp.aws/tree/master/docs
homepage: https://github.com/coll-test/netapp.aws
issues: https://github.com/coll-test/netapp.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
